[package]
name = "server"
version = "0.0.0"
authors = ["Fabien <fabien.ogli@etu.univ-lyon1.fr>"]

[dependencies]
gotham = "0.2.1"
hyper = "0.11"
futures = "0.1"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "1.3.3", features = ["mysql"] }
dotenv = "0.9.0"
